Add debug

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,6 +35,14 @@ jobs:
             oci --version
 
       - run:
+        name: Verify fingerprint env-var is being used
+        command: |
+          echo "OCI_FINGERPRINT (env-var): $OCI_FINGERPRINT"
+          echo "Config file contents:"
+          grep fingerprint ~/.oci/config || echo "fingerprint line missing!"
+
+
+      - run:
           name: Set up OCI config and secure it
           command: |
             mkdir -p ~/.oci
